version: 2
jobs:
  build:
    docker: 
    - circleci/node4.8.2
    steps:
      - checkout
      - run
        name: "'run' statements can actually contain a 'name' and 'command' argument as well"
        command: echo "You can even have multiline commands."
